# Generated by Django 3.1.2 on 2020-11-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20201126_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='v_item',
            name='description',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
